networks:
  parkingnetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 192.18.0.0/16

services:
  estacionamiento-db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '09112'
      MYSQL_DATABASE: 'estDBFingerPrint'
      MYSQL_USER: 'alextcw'
      MYSQL_PASSWORD: '09112'
    networks:
      parkingnetwork:
        ipv4_address: 192.18.0.10
    ports:
      - '3306:3306'
    volumes:
      - /var/lib/jenkins/workspace/mysql_data:/var/lib/mysql

  admin-backend:
    image: alextcw/admin-parking:v2.0
    restart: always
    networks:
      parkingnetwork:
        ipv4_address: 192.18.0.20
    ports:
      - '8080:8080'
    depends_on:
      - estacionamiento-db
    volumes:
      - /var/lib/jenkins/workspace/GitHubActuator/images-data:/home/alextcw/Files/images

  admin-frontend:
    image: alextcw/admin-p-app-parking:v1.0
    restart: always
    networks:
      parkingnetwork:
        ipv4_address: 192.18.0.30
    ports:
      - '4200:4200'
    depends_on:
      - admin-backend
      
  qr-generator:
    image: alextcw/qr-generator:v1.0
    restart: always
    networks:
      parkingnetwork:
        ipv4_address: 192.18.0.40
    ports:
      - '8100:8100'
    depends_on:
      - admin-frontend
